# ESPHome sample configuration using vl6180x sensor.

esphome:
  includes:
    - "vl6180x_sensor.h"
  libraries:
    - SPI
    - Wire
    - adafruit/Adafruit BusIO @ 1.9.6
    - "Adafruit_VL6180X"

i2c:

sensor:
  - platform: custom
    lambda: |-
      auto vl6180x_sensor = new VL6180XSensor();
      App.register_component(vl6180x_sensor);
      return {vl6180x_sensor->distance_sensor};
    sensors:
      - name: "Distance"
        unit_of_measurement: mm
        accuracy_decimals: 0
        filters:
          sliding_window_moving_average:
            window_size: 10
            send_every: 5
            send_first_at: 1
